
package gui;

import com.mycompany.proyecto1.Profesor;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CrearProfesor extends javax.swing.JFrame {
    public AdministradorMainFrame adminMainFrame;
    private List<Profesor> profesores;
    
    /**
     * Creates new form CrearProfesorFrame
     */
    public CrearProfesor(AdministradorMainFrame adminMainFrame, List<Profesor> profesores) {
        initComponents();
        
        int rojo = 255; 
        int verde = 187; 
        int azul = 92;
        Color miColorPersonalizado = new Color(rojo, verde, azul);
        this.getContentPane().setBackground(miColorPersonalizado);
        this.setVisible(true); //Hace visible la ventana
        this.dispose();
        this.setLocationRelativeTo(null); //La coloca al centro
        this.setResizable(false); //Bloquea el redimensionamiento de la ventana
        this.setTitle("Agregar Profesor"); //Título a la ventana
        this.adminMainFrame = adminMainFrame;
        this.profesores = profesores;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selectorGeneroCBox = new javax.swing.JComboBox<>();
        agregarProfesorButton = new javax.swing.JButton();
        codigoProfesorTextField = new javax.swing.JTextField();
        nombreProfesorTextField = new javax.swing.JTextField();
        apellidoProfesorTextField = new javax.swing.JTextField();
        correoProfesorTextField = new javax.swing.JTextField();
        passwordProfeTextField = new javax.swing.JTextField();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar Nuevo Profesor");

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Correo");

        jLabel6.setText("Contraseña");

        jLabel7.setText("Género");

        selectorGeneroCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        selectorGeneroCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorGeneroCBoxActionPerformed(evt);
            }
        });

        agregarProfesorButton.setText("Agregar Profesor");
        agregarProfesorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProfesorButtonActionPerformed(evt);
            }
        });

        correoProfesorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoProfesorTextFieldActionPerformed(evt);
            }
        });

        passwordProfeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordProfeTextFieldActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(selectorGeneroCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreProfesorTextField)
                            .addComponent(apellidoProfesorTextField)
                            .addComponent(correoProfesorTextField)
                            .addComponent(passwordProfeTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoProfesorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarProfesorButton)
                        .addGap(18, 18, 18)
                        .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoProfesorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreProfesorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(apellidoProfesorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(correoProfesorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordProfeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorGeneroCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarProfesorButton)
                    .addComponent(salirButton))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProfesorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProfesorButtonActionPerformed
        try {
    int codigo = Integer.parseInt(codigoProfesorTextField.getText());
    String nombre = nombreProfesorTextField.getText();
    String apellido = apellidoProfesorTextField.getText();
    String correo = correoProfesorTextField.getText();
    String genero = selectorGeneroCBox.getSelectedItem().toString();
    String passwordPersona = passwordProfeTextField.getText();
    
    // Asigna la contraseña predeterminada "1234" si no se proporciona una contraseña
    String contrasenaAsignada = (passwordPersona.isEmpty()) ? "1234" : passwordPersona;

    // Crea una instancia de Profesor con los valores ingresados
    Profesor nuevoProfesor = new Profesor(codigo, nombre, apellido, correo, genero, passwordPersona, contrasenaAsignada); 

    // Agrega el nuevo profesor a la lista
    profesores.add(nuevoProfesor);
    
    // Actualiza la tabla
    adminMainFrame.LlenarTablaProfesores(profesores);
    
    JOptionPane.showMessageDialog(this, "Profesor agregado con éxito.");
    
    this.setVisible(false);

    // Haz visible nuevamente la ventana del menú del administrador
    adminMainFrame.setVisible(true);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Ingrese valores válidos en los campos numéricos.");
}
    }//GEN-LAST:event_agregarProfesorButtonActionPerformed

    private void correoProfesorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoProfesorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoProfesorTextFieldActionPerformed

    private void passwordProfeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordProfeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordProfeTextFieldActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        AdministradorMainFrame crearProfesor = new AdministradorMainFrame();
        crearProfesor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void selectorGeneroCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorGeneroCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorGeneroCBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorMainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProfesorButton;
    private javax.swing.JTextField apellidoProfesorTextField;
    private javax.swing.JTextField codigoProfesorTextField;
    private javax.swing.JTextField correoProfesorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreProfesorTextField;
    private javax.swing.JTextField passwordProfeTextField;
    private javax.swing.JButton salirButton;
    private javax.swing.JComboBox<String> selectorGeneroCBox;
    // End of variables declaration//GEN-END:variables
}
